project:
  type: website
  output-dir: docs

website:
  title: "Antonio Jesús Pérez-Luque"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posts.qmd
        text: Blog
      - href: datasets.qmd
        text: Datasets

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



