project:
  type: website
  output-dir: docs

website:
  title: "Antonio J. Pérez-Luque"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects
      - href: posts.qmd
        text: Blog
      - href: datasets.qmd
        text: Datasets

format:
  html:
    theme: 
      - yeti
      - custom.scss
    css: 
      - styles.css
    toc: true


