project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Antonio J. Pérez-Luque"
  site-url: "https://ajperezluque.com/"
  navbar:
    left:
      - href: publications.qmd
        text: "{{< fa book-open >}} Publications" 
      - href: projects.qmd
        text: "{{< fa chart-line >}} Projects"
      - href: posts.qmd
        text: "{{< fa feather-pointed >}} Blog"
      - href: software.qmd
        text: "{{< fa gear >}} Software"
      - href: datasets.qmd
        text: "{{< fa table >}} Datasets"
      - href: labnotebooks.qmd
        text: "{{< fa flask >}} Lab's notebooks"

format:
  html:
    theme: 
      - yeti
      - custom.scss
    css: 
      - styles.css
    toc: true
