project:
  type: website
  output-dir: docs

website:
  title: "Antonio J. Pérez-Luque"
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa house-user >}} Home"
      - about.qmd
      - href: projects.qmd
        text: "{{< fa chart-line >}} Projects"
      - href: posts.qmd
        text: "{{< fa feather-pointed >}} Blog"
      - href: publications.qmd
        text: Publications
      - href: datasets.qmd
        text: "{{< fa table >}} Datasets"

format:
  html:
    theme: 
      - yeti
      - custom.scss
    css: 
      - styles.css
    toc: true


